"""4

Revision ID: 4d09e1b5b2e0
Revises: 3564645643de
Create Date: 2024-02-13 11:45:53.484676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d09e1b5b2e0'
down_revision: Union[str, None] = '3564645643de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'author_id')
    # ### end Alembic commands ###
