"""7

Revision ID: d1e1c9871701
Revises: 839c7c731039
Create Date: 2024-02-11 00:06:21.350455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e1c9871701'
down_revision: Union[str, None] = '839c7c731039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_author_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_author_fkey', 'comment', 'user', ['author'], ['username'])
    op.drop_column('comment', 'author_id')
    # ### end Alembic commands ###
